<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>CinematicPoker.Simulation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CinematicPoker.Engine/CinematicPoker.Engine.csproj" />
  </ItemGroup>

</Project>
